spring.application.name=Think-Calc-Loop
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=todo_workspace_app;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.integration.webhook-enabled=false
app.integration.webhook-url=
